// automatically generated by the FlatBuffers compiler, do not modify

package edu.vanderbilt.kharesp.zmq.types;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class DataSample extends Table {
  public static DataSample getRootAsDataSample(ByteBuffer _bb) { return getRootAsDataSample(_bb, new DataSample()); }
  public static DataSample getRootAsDataSample(ByteBuffer _bb, DataSample obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public DataSample __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int sampleId() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long sourceTs() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public byte payload(int j) { int o = __offset(8); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int payloadLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer payloadAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }

  public static int createDataSample(FlatBufferBuilder builder,
      int sampleId,
      long sourceTs,
      int payloadOffset) {
    builder.startObject(3);
    DataSample.addSourceTs(builder, sourceTs);
    DataSample.addPayload(builder, payloadOffset);
    DataSample.addSampleId(builder, sampleId);
    return DataSample.endDataSample(builder);
  }

  public static void startDataSample(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addSampleId(FlatBufferBuilder builder, int sampleId) { builder.addInt(0, sampleId, 0); }
  public static void addSourceTs(FlatBufferBuilder builder, long sourceTs) { builder.addLong(1, sourceTs, 0L); }
  public static void addPayload(FlatBufferBuilder builder, int payloadOffset) { builder.addOffset(2, payloadOffset, 0); }
  public static int createPayloadVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startPayloadVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endDataSample(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

